//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CalısmaEntities : DbContext
    {
        public CalısmaEntities()
            : base("name=CalısmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Kategoriler> tbl_Kategoriler { get; set; }
        public virtual DbSet<tbl_Urunler> tbl_Urunler { get; set; }
    
        public virtual int gp_AdvUrunEkle(string kod, string ad, string renk, Nullable<decimal> fiyat)
        {
            var kodParameter = kod != null ?
                new ObjectParameter("kod", kod) :
                new ObjectParameter("kod", typeof(string));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var renkParameter = renk != null ?
                new ObjectParameter("renk", renk) :
                new ObjectParameter("renk", typeof(string));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("fiyat", fiyat) :
                new ObjectParameter("fiyat", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("gp_AdvUrunEkle", kodParameter, adParameter, renkParameter, fiyatParameter);
        }
    }
}
